---
title: "Función 5"
author: "Lucas"
date: "2025-04-10"
output: html_document
---

# CLUTCH

```{r}
get_player_clutch_stats <- function(player_name, season = "2023-24",season_type_all_star = "Regular Season", clutch_time = "Last 5 Minutes", ahead_behind = "Ahead or Behind", point_diff = 5) {
  cat("🧊 Obteniendo estadísticas clutch para:", player_name, "\n")
  
  player_list <- common$get_players()
  player <- Filter(function(p) tolower(p$full_name) == tolower(player_name), player_list)
  if (length(player) == 0) {
    cat("❌ Jugador no encontrado.\n")
    return(NULL)
  }
  
  player_id <- player[[1]]$id
  Sys.sleep(1)
  
  clutch_stats <- nba_api$playerdashboardbyclutch$PlayerDashboardByClutch(
    player_id = player_id,
    season = season,
    season_type_all_star = "Regular Season",
    clutch_time = "Last 5 Minutes",
    ahead_behind = "Ahead or Behind",
    point_diff = 5
  )
  
  clutch_df <- lapply(clutch_stats$get_data_frames(), py_to_r)
  names(clutch_df) <- c("overall", "splits")
  
  cat("✅ Estadísticas clutch descargadas.\n")
  return(clutch_df)
}

```


```{r}
clutch <- get_player_clutch_stats("Stephen Curry")
```




